name: cronometro_flotante
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  floating: ^2.0.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_colorpicker: ^1.0.3

flutter:
  uses-material-design: true
